name: Static Checks & Tests
on: push
jobs:
  RunTests:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry Dependencies
        run: |
          pip install -U pip "poetry>=1.1.5,<2.0.0"
          poetry install
      - name: Run Style Checks
        run: |
          poetry run black --check frugal_freighter/
          poetry run black --check tests/
      - name: Run Linting
        run: |
          poetry run pylint frugal_freighter/
          poetry run pylint tests/
      - name: Run Type Checks
        run: |
          poetry run mypy frugal_freighter/
          poetry run mypy tests/
      - name: Run Dependency Check
        run: |
          poetry run safety check
      - name: Run Unit Tests
        run: |
          poetry run pytest
      - name: Report code coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
